// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXz3TSqnZoQZyYXRdp7O5xrBb6OGDuyY0',
    appId: '1:465224439557:web:75316c17ee489683f6896c',
    messagingSenderId: '465224439557',
    projectId: 'registro-docente-app',
    authDomain: 'registro-docente-app.firebaseapp.com',
    storageBucket: 'registro-docente-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBccUeMJncwRnVtt2xrnUc18M3yWk8ty4o',
    appId: '1:465224439557:android:93650b3862530fe5f6896c',
    messagingSenderId: '465224439557',
    projectId: 'registro-docente-app',
    storageBucket: 'registro-docente-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgYN_KqkupDJbmE0b7i9IA_jSoQYBZ1s0',
    appId: '1:465224439557:ios:387ace115eb673a8f6896c',
    messagingSenderId: '465224439557',
    projectId: 'registro-docente-app',
    storageBucket: 'registro-docente-app.firebasestorage.app',
    iosBundleId: 'online.registrodocente.registrodocente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgYN_KqkupDJbmE0b7i9IA_jSoQYBZ1s0',
    appId: '1:465224439557:ios:387ace115eb673a8f6896c',
    messagingSenderId: '465224439557',
    projectId: 'registro-docente-app',
    storageBucket: 'registro-docente-app.firebasestorage.app',
    iosBundleId: 'online.registrodocente.registrodocente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXz3TSqnZoQZyYXRdp7O5xrBb6OGDuyY0',
    appId: '1:465224439557:web:7323255d2c168c11f6896c',
    messagingSenderId: '465224439557',
    projectId: 'registro-docente-app',
    authDomain: 'registro-docente-app.firebaseapp.com',
    storageBucket: 'registro-docente-app.firebasestorage.app',
  );
}
